<a href="https://colab.research.google.com/github/main-scientist/course_data_base/blob/main/croud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import random
import pandas as pd
import numpy as np

In [114]:
data = pd.read_html('https://bmstu.ru/bachelor/previous-points?ysclid=lgpdodbo5c867324')

In [115]:
df = data[0]

In [116]:
df

    Наименование направления подготовки (специальности) – НП(С) Код НП(С)  \
    Наименование направления подготовки (специальности) – НП(С) Код НП(С)
0    Автоматизация технологических процессов и прои...           15.03.04
1    Безопасность информационных технологий в право...           10.05.05
2                                   Бизнес-информатика           38.03.05
3                                   Бизнес-информатика           38.03.05
4                  Биотехнические системы и технологии           12.03.04
..                                                 ...                ...
118                 Электроэнергетика и электротехника           13.03.02
119                 Электроэнергетика и электротехника           13.03.02
120                      Энергетическое машиностроение           13.03.03
121                      Энергетическое машиностроение           13.03.03
122                       Ядерные реакторы и материалы           14.05.01

    Квалификация Факультет Кафедра 2022      2021      2020      2019       \
    Квалификация Факультет Кафедра   ОК   ЦП   ОК   ЦП   ОК   ЦП   ОК   ЦП
0       Бакалавр        РК     РК9  265  223  266  204  237  239  271  234
1     Специалист        ЮР      Юр  256  207    —    —    —    —    —    —
2       Бакалавр       ИБМ    ИБМ6  278  216  274  272  274  261  254  224
3       Бакалавр       ИБМ    ИБМ3    —    —    —    —    —    —    —    —
4       Бакалавр       БМТ    БМТ1  272  226  295  277  283  236  295  260
..           ...       ...     ...  ...  ...  ...  ...  ...  ...  ...  ...
118     Бакалавр        СМ    СМ10  207  198  254  196  226    —    —    —
119     Бакалавр         Э      Э2  149    —  257    —  230    —  165  241
120     Бакалавр         Э      Э2  216  174  212  191  187  156  222  191
121     Бакалавр         Э     Э10  159  174  234  229  236  199  240  219
122   Специалист         Э      Э7  189  160  236  185  172  179  251  251

    2018      2017
      ОК   ЦП   ОК   ЦП
0    251  212  264  174
1      —    —    —    —
2      —    —    —    —
3      —    —    —    —
4    282  223  279  228
..   ...  ...  ...  ...
118    —    —    —    —
119    —    —    —    —
120  218  183  231  198
121  231  199  233  180
122  235  205  228  186

[123 rows x 17 columns]

In [117]:
df.drop(columns=['Код НП(С)', 'Факультет', 'Кафедра'], inplace=True)

<ipython-input-117-1f517da20714>:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df.drop(columns=['Код НП(С)', 'Факультет', 'Кафедра'], inplace=True)

In [118]:
df.rename(columns = {'Наименование направления подготовки (специальности) – НП(С)':'direction', 'Квалификация':'qualification'}, inplace=True)

In [119]:
df

                                             direction qualification 2022  \
                                             direction qualification   ОК
0    Автоматизация технологических процессов и прои...      Бакалавр  265
1    Безопасность информационных технологий в право...    Специалист  256
2                                   Бизнес-информатика      Бакалавр  278
3                                   Бизнес-информатика      Бакалавр    —
4                  Биотехнические системы и технологии      Бакалавр  272
..                                                 ...           ...  ...
118                 Электроэнергетика и электротехника      Бакалавр  207
119                 Электроэнергетика и электротехника      Бакалавр  149
120                      Энергетическое машиностроение      Бакалавр  216
121                      Энергетическое машиностроение      Бакалавр  159
122                       Ядерные реакторы и материалы    Специалист  189

         2021      2020      2019      2018      2017
      ЦП   ОК   ЦП   ОК   ЦП   ОК   ЦП   ОК   ЦП   ОК   ЦП
0    223  266  204  237  239  271  234  251  212  264  174
1    207    —    —    —    —    —    —    —    —    —    —
2    216  274  272  274  261  254  224    —    —    —    —
3      —    —    —    —    —    —    —    —    —    —    —
4    226  295  277  283  236  295  260  282  223  279  228
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
118  198  254  196  226    —    —    —    —    —    —    —
119    —  257    —  230    —  165  241    —    —    —    —
120  174  212  191  187  156  222  191  218  183  231  198
121  174  234  229  236  199  240  219  231  199  233  180
122  160  236  185  172  179  251  251  235  205  228  186

[123 rows x 14 columns]

In [120]:
direction_df =  df.xs('direction', axis=1, level=1)
qualification_df = df.xs('qualification', axis=1, level=1)
df_2022 = df[('2022', 'ОК')]
df_2021 = df[('2021', 'ОК')]
df_2020 = df[('2020', 'ОК')]
df_2019 = df[('2019', 'ОК')]
df_2018 = df[('2018', 'ОК')]
df_2017 = df[('2017', 'ОК')]

new_df = pd.DataFrame(pd.concat([direction_df, qualification_df, df_2022, df_2021, df_2020, df_2019, df_2018, df_2017], axis=1))
new_df.columns = ['direction', 'qualification', '2022', '2021', '2020', '2019', '2018', '2017']
new_df

,direction,qualification,2022,2021,2020,2019,2018,2017
0,Автоматизация технологических процессов и прои...,Бакалавр,265,266,237,271,251,264
1,Безопасность информационных технологий в право...,Специалист,256,—,—,—,—,—
2,Бизнес-информатика,Бакалавр,278,274,274,254,—,—
3,Бизнес-информатика,Бакалавр,—,—,—,—,—,—
4,Биотехнические системы и технологии,Бакалавр,272,295,283,295,282,279
...,...,...,...,...,...,...,...,...
118,Электроэнергетика и электротехника,Бакалавр,207,254,226,—,—,—
119,Электроэнергетика и электротехника,Бакалавр,149,257,230,165,—,—
120,Энергетическое машиностроение,Бакалавр,216,212,187,222,218,231
121,Энергетическое машиностроение,Бакалавр,159,234,236,240,231,233
122,Ядерные реакторы и материалы,Специалист,189,236,172,251,235,228

In [126]:
new_df.drop(new_df[new_df['qualification'] == 'Специалист'].index, inplace=True)
new_df.reset_index(drop=True, inplace=True)
new_df

,direction,qualification,2022,2021,2020,2019,2018,2017
0,Автоматизация технологических процессов и прои...,Бакалавр,265,266,237,271,251,264
1,Бизнес-информатика,Бакалавр,278,274,274,254,—,—
2,Бизнес-информатика,Бакалавр,—,—,—,—,—,—
3,Биотехнические системы и технологии,Бакалавр,272,295,283,295,282,279
4,Биотехнические системы и технологии,Бакалавр,225,260,263,234,259,255
...,...,...,...,...,...,...,...,...
65,Электроника и наноэлектроника,Бакалавр,226,246,241,257,230,214
66,Электроэнергетика и электротехника,Бакалавр,207,254,226,—,—,—
67,Электроэнергетика и электротехника,Бакалавр,149,257,230,165,—,—
68,Энергетическое машиностроение,Бакалавр,216,212,187,222,218,231
69,Энергетическое машиностроение,Бакалавр,159,234,236,240,231,233

In [137]:
directions = ['Автоматизация технологических процессов и производств', 'Бизнес-информатика', 'Информатика и вычислительная техника', 
              'Информационные системы и технологии', 'Математика и компьютерные науки', 'Прикладная информатика', 'Прикладная математика',
              'Прикладная математика и информатика', 'Ракетные комплексы и космонавтика']
new_df['direction'].unique()

array(['Автоматизация технологических процессов и производств',
       'Бизнес-информатика', 'Биотехнические системы и технологии',
       'Высокотехнологичные плазменные и энергетические установки',
       'Дизайн', 'Инноватика', 'Информатика и вычислительная техника',
       'Информационные системы и технологии',
       'Конструирование и технология электронных средств',
       'Лазерная техника и лазерные технологии', 'Лингвистика',
       'Математика и компьютерные науки',
       'Материаловедение и технология материалов', 'Машиностроение',
       'Менеджмент', 'Механика и математическое моделирование',
       'Мехатроника и робототехника', 'Наноинженерия', 'Оптотехника',
       'Прикладная информатика', 'Прикладная математика',
       'Прикладная математика и информатика', 'Прикладная механика',
       'Программная инженерия', 'Ракетные комплексы и космонавтика',
       'Социология', 'Стандартизация и метрология', 'Техническая физика',
       'Технологические машины и оборудование',
       'Техносферная безопасность', 'Управление в технических системах',
       'Фундаментальная и прикладная лингвистика',
       'Холодильная, криогенная техника и системы жизнеобеспечения',
       'Экономика', 'Электроника и наноэлектроника',
       'Электроэнергетика и электротехника',
       'Энергетическое машиностроение'], dtype=object)

In [138]:
new_df[new_df['direction'].isin(directions)]

,direction,qualification,2022,2021,2020,2019,2018,2017
0,Автоматизация технологических процессов и прои...,Бакалавр,265,266,237,271,251,264
1,Бизнес-информатика,Бакалавр,278,274,274,254,—,—
2,Бизнес-информатика,Бакалавр,—,—,—,—,—,—
13,Информатика и вычислительная техника,Бакалавр,291,289,284,280,278,275
14,Информатика и вычислительная техника,Бакалавр,287,287,281,283,273,286
15,Информатика и вычислительная техника,Бакалавр,261,281,261,276,256,267
16,Информатика и вычислительная техника,Бакалавр,257,277,259,275,255,266
17,Информационные системы и технологии,Бакалавр,247,277,257,272,255,270
22,Математика и компьютерные науки,Бакалавр,228,271,257,259,257,—
23,Математика и компьютерные науки,Бакалавр,269,273,268,270,257,257
41,Прикладная информатика,Бакалавр,293,287,279,279,274,272
42,Прикладная информатика,Бакалавр,257,277,258,273,243,259
43,Прикладная информатика,Бакалавр,258,275,—,—,—,—
44,Прикладная информатика,Бакалавр,277,284,—,—,—,—
45,Прикладная математика,Бакалавр,265,271,236,269,258,250
46,Прикладная математика,Бакалавр,255,271,253,268,260,249
47,Прикладная математика,Бакалавр,278,279,258,263,255,250
48,Прикладная математика,Бакалавр,—,—,—,—,—,—
49,Прикладная математика и информатика,Бакалавр,272,290,282,283,268,277
52,Ракетные комплексы и космонавтика,Бакалавр,242,269,265,269,265,264
53,Ракетные комплексы и космонавтика,Бакалавр,221,190,242,252,244,242